---
title: "Bivariate Viz"
execute: 
  echo: false
  warning: false
  error: false
---

Use this file to generate a professional looking **bivariate** visualization.  The visualization will not perfect the first time but you are expected to improve it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
#Importing data
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv") 
```

```{r}
#Downloading tidyverse
library(tidyverse)
```

```{r}
#Create bivariate visualization!
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density(alpha = 0.4) +
  scale_fill_manual(values = c("blue", "purple", "red"))+
  labs( y = "Density of Votes", 
        x = "Percentage of Republican Votes", 
        fill = "Historical County Type", 
        title = "Comparative Density of Republican Percentages by Historical County Types")
```


```{r}
# Different data set!
# Load tidyverse package for plotting and wrangling
library(tidyverse)

# Import the data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))
```


```{r}
#Plot with accessibility features: alternative captions via #| fig-___ and color scale that is okay for color blind people via scale_color_viridis_c (c is for continuous, d is for discrete).

#| fig-cap: "Density plots of Temperatures in 3 Australian locations."
#| fig-alt: "Density plots of Temperatures in 3 Australian locations."

ggplot(weather, aes(y = temp3pm, x = temp9am, color = maxtemp)) + 
  geom_point(alpha = 0.5) + 
  labs(x = "Morning Temperature (F)",
       y = "Afternoon Temperature (F)", 
       color = "Maximum Temperature (F)") + 
  scale_color_viridis_c()+
  theme_minimal()
```
