---
title: "Exam 2: Food Consumption2"
number-sections: true
execute: 
  warning: false
fig-env: 'figure'
fig-pos: 'h'
fig-align: center
code-fold: false
---

```{r}
#Load packages
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth)
library(sf)
```

```{r}
#Load data
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
```

```{r}
#Inspect data
str(fc)
```

```{r}
head(fc, 22)
```

```{r}
#Fix food_category variable
fcc <- fc |> 
  mutate (food_category = fct_recode (food_category, 
                                      "Lamb" = "Lamb & Goat",
                                      "Dairy" = "Milk - inc. cheese",
                                      "Wheat" = "Wheat and Wheat Products",
                                      "Nuts" = "Nuts inc. Peanut Butter"))
```

```{r}
#Most Consuming Countries
fcc |> 
  group_by(country) |>
  summarize(total_consumption = sum(consumption)) |>
  arrange (desc(total_consumption)) |>
  select(country, total_consumption) |>
  head(5) 
```

```{r}
#Visualization
fcc |> 
  group_by(country) |>
  summarize(total_consumption = sum(consumption)) |>
  arrange (desc(total_consumption)) |>
  select(country, total_consumption) |>
  filter(country %in% c("Finland", "Lithuania", "Sweden", "Netherlands", "Albania")) |>
  ggplot(aes(x = fct_reorder(country, total_consumption), y = total_consumption)) +  
  geom_col(fill = "darkblue", color = "pink")+
  labs(x = "Country", y = "Total Consumption")+
  theme_minimal()
```

